### ISSUE TITLE
Add "Legacy Paint" support

### ISSUE THREAD

**Issue by idinium96** [ZeusJunior/node-tf2-backpack#1]
As you may already know, there are painted stuff with Team Spirit but with a missing blue attribute.
It would be nice to also include that, probably just by adding the `B8383B` key color on the `PrimaryColor` object here:
https://github.com/ZeusJunior/node-tf2-backpack/blob/11c31d588df0d4b40a3be15e25b1ff7dcbbe6faa/src/data.ts#L173-L206

And, it's up to the user how to determine whether it's a Legacy Paint or Team Spirit (or better it will automatically parsed)

**Comment by idinium96** [comment]
Some more context:
![image](https://user-images.githubusercontent.com/47635037/212929121-f259f175-74d5-46bb-8bb6-240f8ade6dbb.png)
![image](https://user-images.githubusercontent.com/47635037/212929130-c21353e3-9564-4892-9595-0cfd6fe9a8c6.png)

**Comment by ZeusJunior** [comment]
Fixed in v1.1.6
You can just input the paint and paint_other in the same place as before the fix, doesn't matter if one is null/undefined.

For some background:
Any of the team coloured paints can miss either the RED or BLU attribute. 
Most commonly is the BLU attribute missing (like your example). On steam it has the paint icon but no description stating its painted, functions the same as the regular paint.
More rare is the RED attribute missing. Doesn't display the paint icon or a description on steam but in game shows just half a paint icon and it only works on BLU team.

How? Idunno man 🤷‍♂️

**Comment by idinium96** [comment]
Great! Thank you very much for the update, and thank you too for the extra info.
